name: Auto Update when upstream releases
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch release version
        id: upstream
        run: |
          echo ::set-output name=release_tag::$(curl "https://api.github.com/repos/PKief/vscode-material-icon-theme/commits?per_page=100" \
          | jq '.[] | .commit.message' \
          | grep -m 1 -oP '^"Release\s+\K(\d+\.\d+\.\d+)')
          echo ::set-output name=current_tag::$(<upstream.version)

      - name: Attempt update
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        run: npm run update

      - name: Get package version
        id: package-version
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        run: echo ::set-output name=package_version::v$(jq -r .version package.json)

      - name: Commit updated files
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: '[auto] update to upstream ${{steps.upstream.outputs.release_tag}}'
          tag: '${{steps.package-version.outputs.package_version}}'

      - name: Release
        if: steps.upstream.outputs.release_tag != steps.upstream.outputs.current_tag
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{steps.package-version.outputs.package_version}}'
          body: Built with icons from VSCode Material Icon Theme ${{steps.upstream.outputs.release_tag}}
          files: '*.zip'
